# Generated by Django 5.1.2 on 2024-11-08 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0003_alter_tblaltaproyecto_folio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblaltaproyecto',
            name='GastoTotal',
        ),
        migrations.AddField(
            model_name='tblproyecto',
            name='Presupuesto',
            field=models.FloatField(null=True),
        ),
    ]
