# Generated by Django 5.1.2 on 2024-11-09 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0004_remove_tblaltaproyecto_gastototal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblproyecto',
            name='Presupuesto',
        ),
        migrations.AddField(
            model_name='tblaltaproyecto',
            name='Presupuesto',
            field=models.FloatField(null=True),
        ),
    ]
