# Generated by Django 5.1.2 on 2024-11-13 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0005_remove_tblproyecto_presupuesto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblAreaDeTrabajo',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='tblaltaproyecto',
            name='IDAreaTrabajo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tblareadetrabajo'),
        ),
        migrations.AddField(
            model_name='tblcategoriagasto',
            name='IDAreaTrabajo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tblareadetrabajo'),
        ),
        migrations.AddField(
            model_name='tblcliente',
            name='IDAreaTrabajo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tblareadetrabajo'),
        ),
        migrations.AddField(
            model_name='tblformapago',
            name='IDAreaTrabajo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tblareadetrabajo'),
        ),
    ]
