# Generated by Django 5.1.2 on 2024-11-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0007_tblproyecto_idareatrabajo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblaltaproyecto',
            name='Presupuesto',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
