# Generated by Django 5.1.2 on 2024-11-21 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0009_alter_tblproyecto_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblaltaproyecto',
            name='Presupuesto',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='tblproyecto',
            name='Monto',
            field=models.FloatField(null=True),
        ),
    ]
